version: "3.7"

services:

  dev-db:
    container_name: dev-db
    image: postgres:12.7
    restart: always
    environment:
      - POSTGRES_USER=qwerty007
      - POSTGRES_PASSWORD=qwerty007
      - POSTGRES_DB=devDB
    command: ["--autovacuum=off"]
    ports:
      - "127.0.0.12:5434:5432"

