server:
  logging:
    stacktrace:
      enabled: ${LOGGING_STACKTRACE:true}
      deep: 5
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:someDb}?ApplicationName=krst-projects&sslmode=${DB_SSL_MODE:disable}&prepareThreshold=0
    username: ${DB_USERNAME:qwerty007}
    password: ${DB_PASSWORD:qwerty007}
    driver-class-name: org.postgresql.Driver
